Switch to C++20 to prevent warning 'variadic-macro-arguments-omitted'
error: passing no argument for the '...' parameter of a variadic macro is a C++20 extension [-Werror,-Wvariadic-macro-arguments-omitted]